# Тестирование

Тестирование основного функционала проекта

## Libs

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
os.chdir("../")

In [9]:
import datetime
import logging
logging.basicConfig(
	level=logging.INFO,
	format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

## Testing

### Engines (DONE)

In [6]:
from src.api.reference.engines import EnginesApi
engines_api = EnginesApi()
engines_api.get_data().head()

2026-02-10 20:27:07,837 - EnginesApi - INFO - Данные сохранены в data/metadata/engines.csv

  id       name                             title
0  1      stock  Фондовый рынок и рынок депозитов
1  2      state            Рынок ГЦБ (размещение)
2  3   currency                    Валютный рынок
3  4    futures                     Срочный рынок
4  5  commodity                    Товарный рынок

### Markets (DONE)

In [7]:
from src.api.reference.markets import MarketsApi
markets_api = MarketsApi()
markets_api.get_data().head(5)

2026-02-10 20:27:10,619 - MarketsApi - INFO - Данные сохранены в data/metadata/markets.csv

,engine_id,engine_name,engine_title,id,NAME,title
0,1,stock,Фондовый рынок и рынок депозитов,5,index,Индексы фондового рынка
1,1,stock,Фондовый рынок и рынок депозитов,1,shares,Рынок акций
2,1,stock,Фондовый рынок и рынок депозитов,2,bonds,Рынок облигаций
3,1,stock,Фондовый рынок и рынок депозитов,4,ndm,Режим переговорных сделок
4,1,stock,Фондовый рынок и рынок депозитов,29,otc,ОТС

### MarketValidator (DONE)

In [8]:
from src.api.validator import MarketValidator

market_validator = MarketValidator()
print(market_validator.get_combinations_table())

ENGINE          -> MARKETS
--------------------------------------------------
stock           -> shares, bonds, index, ndmsec, currency
currency        -> selt, fixing, indices
futures         -> forts, options, futures
commodity       -> commodity, standard
state           -> agriculture, exchange
repo            -> repo, deposit
bonds           -> bonds, main
offboard        -> qnv, main

### HistoryApi (DONE)

In [10]:
from src.api.history.history import HistoryApi

history_api = HistoryApi()
history_api.get_data(
	market_name="shares",
	engine_name="stock",
	start_date=datetime.datetime.strptime("2025-10-10", '%Y-%m-%d'),
	end_date=datetime.datetime.strptime("2025-10-15", '%Y-%m-%d')
).head(5)

2026-02-10 20:27:29,985 - HistoryApi - INFO - Получение данных: engine=stock, market=shares, start=2025-10-10, end=2025-10-15
100%|██████████| 6/6 [00:00<00:00,  9.40it/s]
2026-02-10 20:27:30,646 - HistoryApi - INFO - Данные сохранены в data/history/stock/shares.csv

,BOARDID,TRADEDATE,SHORTNAME,SECID,NUMTRADES,VALUE,OPEN,LOW,HIGH,LEGALCLOSEPRICE,...,MARKETPRICE3,ADMITTEDQUOTE,MP2VALTRD,MARKETPRICE3TRADESVALUE,ADMITTEDVALUE,WAVAL,TRADINGSESSION,CURRENCYID,TRENDCLSPR,TRADE_SESSION_DATE
399,SMAL,2025-10-15,Фикс Прайс,FIXR,555,36661.18,0.6202,0.493,0.7,,...,,,0,0,,0,3,SUR,-1.51,2025-10-15
336,TQBR,2025-10-15,Арсагера,ARSA,13,30897,9.62,9.62,9.7,9.63,...,9.67,,0,521352,,0,3,SUR,0,2025-10-15
326,TQTF,2025-10-15,AMGB ETF,AMGB,46,140705.8,119.5,118.9,119.8,119.5,...,119.2,,0,500077.2,,3914125.1,3,SUR,0.34,2025-10-15
327,TQTF,2025-10-15,AMGL ETF,AMGL,79,7978891.8,128.3,127.2,128.3,127.5,...,127.9,,973231.6,973231.6,,15228371.65,3,SUR,-0.08,2025-10-15
328,TQTF,2025-10-15,AMNR ETF,AMNR,451,51117160.42,137.064,136.955,137.07,137.067,...,137.069,,46418113.7,46418113.7,,144170557.08,3,SUR,0.04,2025-10-15